### ISSUE TITLE
support for dubs?

### ISSUE THREAD

**Issue by indigomarxist** [justchokingaround/jerry#10]
yes yes i know cringe. but i was wondering if this will ever be supported (something like --dub).

**Comment by justchokingaround** [comment]
mayhaps (i'll check today if it's possible)

**Comment by justchokingaround** [comment]
it is doable, i will probably implement it tomorrow

**Comment by justchokingaround** [comment]
done in https://github.com/justchokingaround/jerry/pull/9/commits/03f6d8f159850beecbe5440318afa80bf9293140 on the `feat-manga` branch. you can either use `jerry --dub` or define it in `jerry.conf` by adding a line like this:
```
dub="true"
```

i will close this issue once i merge the branch into main, still have to test and fix a few things
