### ISSUE TITLE
Can't find Kimetsu no yaiba entertainment district arc

### ISSUE THREAD

**Issue by VMatt013** [justchokingaround/jerry#14]
Hey, I had an issue, that might be a duplicate of #13 , but not really sure of it , because it works fine for every other anime or movie I tried, except for this one.
I tried to change provider, but it gave the same issue with gogoanime too.

![Screenshot_20230410_021325](https://user-images.githubusercontent.com/71434244/230803228-865c88fb-94a4-4ea0-9829-aab0ae952ff6.png)
![Screenshot_20230410_021406](https://user-images.githubusercontent.com/71434244/230803230-3b24f6ba-2f14-4950-a8e8-6a69476d2026.png)
![Screenshot_20230410_021429](https://user-images.githubusercontent.com/71434244/230803234-7a16b3dc-12af-4872-87c2-b58214f950a9.png)

**Comment by justchokingaround** [comment]
![image](https://user-images.githubusercontent.com/44473782/230904448-b05e735d-816c-4c65-8865-54040992f23c.png)
seems to work fine for me, what version are you on?
```sh
jerry -v
```

**Comment by justchokingaround** [comment]
```sh
sh -x $(which jerry) -c 2> idk.log
token=$(cat idk.log | sed -nE "s@.*access_token=(.*)@\1@p" | head -1)
sed -i "/${token}/d" idk.log
```

could you please send me the logs?

**Comment by justchokingaround** [comment]
ah, i fixed that bug in the v4 branch

**Comment by VMatt013** [comment]
Oh, thank you for the quick responds
