### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by diniamo** [justchokingaround/jerry#17]
First of all, mad respect for writing this in bash, I'd have to be insane for that. This is the ideal anime player that I want to use, unfortunately as I said, I don't know bash and I don't want to know too much about it, so I have to make this issue.

1. The search feature seems to be bad all around, if I try to watch an anime from my anilist list, I Just get
```
Loading The Irregular at Magic High School...
Error: The Irregular at Magic High School not found on zoro
```
or if I try to play it from  `watch new` (the selection list pops up, but after selecting the correct one, it exits):
```
Disclaimer: you need to finish the first episode before you can update your progress
Error: the+irregular+at+magic+high not found on zoro
```
2. When I try to update episodes watched, this happens (11 is what I entered):
```
Enter new progress for: The Irregular at Magic High School
Current progress: 10/26 episodes watched
11
/usr/local/bin/jerry: line 230: [: Enter a new episode number: : integer expression expected
/usr/local/bin/jerry: line 231: [: Enter a new episode number: : integer expression expected
Updating progress for The Irregular at Magic High School...
/usr/local/bin/jerry: line 234: [: Enter a new episode number: : integer expression expected
/usr/local/bin/jerry: line 235: Enter a new episode number: : syntax error in expression (error token is "a new episode number: ")
New progress: Enter a new episode number: /26 episodes watched
/usr/local/bin/jerry: line 237: [: Enter a new episode number: : integer expression expected
```
3. The info feature doesn't work without zenity, I get this output:
```

───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN   <EMPTY>
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN   <EMPTY>
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by justchokingaround** [comment]
i'm actually working on a full rewrite from scratch atm, it'll take some time, maybe a week or a bit more, i'll try to finish it asap

**Comment by diniamo** [comment]
Oh, alright then. Will it still be batch?

**Comment by justchokingaround** [comment]
it will be posix shell, yes

**Comment by diniamo** [comment]
Thanks, I'll be waiting

**Comment by justchokingaround** [comment]
if u're interested in following the progress, you can check when i commit to this branch: https://github.com/justchokingaround/jerry/blob/rewrite/jerry.sh

**Comment by justchokingaround** [comment]
@diniamo merged the changes into main. fyi in v1.9.0 of the script (basically a beta version for v2.0.0), the default provider is now 9anime, as it seems to be the most stable. i have not yet documented everything properly, but the `-h` and `--help` argument should give you an idea of what the script can do atm. everything is functional from my testing.

**Comment by diniamo** [comment]
Awesome! Thank you for notifying me. The only thing I noticed is that the console gets spammed with corruption related ffmpeg messages:
```
AV: 00:00:07 / 00:23:42 (1%) A-V:  0.000 Cache: 66s/13MB
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 0, dts = 6872250).
[ffmpeg/demuxer] hls: Packet corrupt (stream = 0, dts = 6868500).
```
everything else seems to work fine.

**Comment by justchokingaround** [comment]
i'll look into supressing those warnings

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/jerry/commit/b1d72754c3c324d7aa5dda26c7e69ff693a22c19 will fix it when it's merged into main
