### ISSUE TITLE
one piece doesnt display the exact episode range

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/jerry#19]
provider zoro
![Screenshot_2023-06-30_14-02-46](https://github.com/justchokingaround/jerry/assets/95531944/fd5be61e-1448-49b0-90bf-c663245fb949)

**Comment by ttx99** [comment]
and detective conan too and probably animes with 1k total of episodes

**Comment by justchokingaround** [comment]
fixed in fe11b1a3c8475cc67882aebab39cfee36c86a6cb and merged into main
