### ISSUE TITLE
How to delete history ? or pls add add -d to delete

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/jerry#20]
how?

**Comment by justchokingaround** [comment]
`rm ~/.local/share/jerry/jerry_history.txt`

i'll add a flag

**Comment by ttx99** [comment]
bro can you guide how to get a anilist token? im curious

**Comment by justchokingaround** [comment]
if you have an anilist account, just run jerry, it will give you a link that you should open in the browser and you will get a token that way, which you can then paste into the terminal (jerry handles practically everything wrt authentication). if you don't wanna bother with creating an anilist account, just set `no_anilist=1` in the config. this is the link to anilist, it is entirely free:
https://anilist.co/

**Comment by ttx99** [comment]
copy ill try tomorrow

**Comment by justchokingaround** [comment]
merged into main `--clear-history | --delete-history`
