### ISSUE TITLE
Set to complete and ask for rating when finished

### ISSUE THREAD

**Issue by diniamo** [justchokingaround/jerry#22]
Small thing, but it would nice for the program to set the anime to completed (I think it already does this but it didn't do it all the time for me?) and ask for a rating instead of just quitting when you finish an anime/manga.

**Comment by justchokingaround** [comment]
makes sense, ill look into it

**Comment by VegardMatthey** [comment]
I have a solution that mostly works. I have not been able to test with manga since it returns "Error - _manga_ not found".
I just made a separate function for this:
`immediate_score() {
    i_total="0"
    if [ $1 = "anime" ]; then
	    i_total="$episodes_total"
    elif [ $1 = "manga" ]; then 
	    i_total="$chapters_total"
    else
	    return
    fi

    printf "$status"
    if [ $(($progress + 1)) = $(echo $i_total | cut -d " " -f1) ]; then
	printf "Enter a score: "
	read -r i_score
    else
	return
    fi

    curl -s -X POST "$anilist_base" \
        -H 'Content-Type: application/json' \
        -H "Authorization: Bearer $access_token" \
	-d "{\"query\":\"mutation(\$id:Int \$mediaId:Int \$status:MediaListStatus \$score:Float \$progress:Int \$progressVolumes:Int \$repeat:Int \$private:Boolean \$notes:String \$customLists:[String]\$hiddenFromStatusLists:Boolean \$advancedScores:[Float]\$startedAt:FuzzyDateInput \$completedAt:FuzzyDateInput){SaveMediaListEntry(id:\$id mediaId:\$mediaId status:\$status score:\$score progress:\$progress progressVolumes:\$progressVolumes repeat:\$repeat private:\$private notes:\$notes customLists:\$customLists hiddenFromStatusLists:\$hiddenFromStatusLists advancedScores:\$advancedScores startedAt:\$startedAt completedAt:\$completedAt){id mediaId status score advancedScores progress progressVolumes repeat priority private hiddenFromStatusLists customLists notes updatedAt startedAt{year month day}completedAt{year month day}user{id name}media{id title{userPreferred}coverImage{large}type format status episodes volumes chapters averageScore popularity isAdult startDate{year}}}}\",\"variables\":{\"score\":\"$i_score\",\"mediaId\":$media_id}}"
}
`
This function is then called in the functions watch_anime_choice and read manga_choice.
One issue with this solution apart from not being well adapted to the rest of the script is that it prints the json of the response.
Note: I have little to no experience with shell.

**Comment by VegardMatthey** [comment]
Just redirecting the output to /dev/null worked, updated the snippet.

**Comment by diniamo** [comment]
Nice.

Yeah I've been using zoro too.

**Comment by diniamo** [comment]
Create a pull request and wait then.

**Comment by justchokingaround** [comment]
done in 123ecdafa94ea545a4e38c172b846febd784f072

**Comment by diniamo** [comment]
Om this seems to only work for normal watching, but I use binge like 99% of the time.

**Comment by VegardMatthey** [comment]
should probably be called in a different place than watch_anime_choice().

**Comment by justchokingaround** [comment]
yeah, that would make sense. i think it would be better to just remove `Watch anime` altogether, and only have binge mode by default. do you wanna PR this @VegardMatthey ? i'm a little busy with exams atm, so i'll only be implementing this in like a week

**Comment by VegardMatthey** [comment]
Yes I can do it.

**Comment by VegardMatthey** [comment]
Just checked the code and tested it myself. The function is being called. @diniamo Are you sure that it does not work for you? If it still does not work share your config.

**Comment by diniamo** [comment]
I mean I've watched multiple animes and updated multiple times, no, it doesn't seem to work

```
player="mpv"
provider="9anime"
video_provider="Vidstream"
base_helper_url="https://9anime.eltik.net"
download_dir="$PWD"
manga_dir="$data_dir/jerry-manga"
manga_format="image"
manga_opener="nsxiv"
history_file="$HOME/.local/share/jerry/jerry_history.txt"
subs_language="english"
use_external_menu=0
image_preview=0
preview_window_size=up:60%:wrap
ueberzug_output=kitty
ueberzug_x=10
ueberzug_y=3
ueberzug_max_width=$(($(tput cols) / 2))
ueberzug_max_height=$(($(tput lines) / 2))
json_output=0
dub=false
```

**Comment by justchokingaround** [comment]
`score_on_completion=true`

should be set

**Comment by justchokingaround** [comment]
no workie otherwise, its disabled by default

**Comment by diniamo** [comment]
Very epic, guess we'll see whether it works when I finish my next anime :^)

**Comment by justchokingaround** [comment]
can you still PR for having only binge mode still, please @VegardMatthey (when u get the time, not urgent)

**Comment by VegardMatthey** [comment]
Yes.

**Comment by VegardMatthey** [comment]
In pull request #27 I removed the ability to watch one episode at a time and replaced it with binge watching. Also I made it so that the program exits when a show is completed.

**Comment by justchokingaround** [comment]
i'll check it out when i get some time, thank you!

**Comment by diniamo** [comment]
![image](https://github.com/justchokingaround/jerry/assets/55629891/2cc83d4e-97cf-4520-9f2c-2417d41fb0e2)
woovies, it worked

**Comment by VegardMatthey** [comment]
I have fixed that

**Comment by diniamo** [comment]
I assumed so, nice
