### ISSUE TITLE
bug: 9anime scraper broken

### ISSUE THREAD

**Issue by justchokingaround** [justchokingaround/jerry#25]
@enimax-anime my discord account has been disabled (idk for how long), so i can't ask you there, but what's the current status on 9anime? i saw that they rebranded to aniwave.to, has the key stuff changed too?

**Comment by enimax-anime** [comment]
Ah, that's unfortunate. It's working. All that's changed is how vizcloud/mcloud are extracted. You gotta send a *POST* request to the `/rawVizcloud` route with the following JSON payload:

1. query: make sure it has the search params (something like XEYL9M0W3JVN?t=4xnZCfIvDF0MyA)
2. futoken: Send a request to https://vidstream.pro/futoken and just send a whole thing

**Comment by justchokingaround** [comment]
![image](https://github.com/justchokingaround/jerry/assets/44473782/d5673e6e-117c-4d1e-aaba-aaccd4b0b55a)
hahaha

alright, thx, i'll try implementing it all in code today then. you should be sleeping :gun:

**Comment by enimax-anime** [comment]
Lol, ikr? I lost my shit when I saw that.

Yeah... I'll go to bed in a bit XD

**Comment by justchokingaround** [comment]
seems like they added cloudflare, that i can't bypass. i can't even get the `data-id`, which is used for query

**Comment by enimax-anime** [comment]
That's really weird. I am pretty sure they don't have cloudflare up. What link are you fetching?

**Comment by justchokingaround** [comment]
well it works now...

they changed it, but basically at the time i was writing that, a POST request was used to get the raw html, something like this:
![image](https://github.com/justchokingaround/jerry/assets/44473782/a7ea939a-2bf0-4397-b5f9-74a10b7e8983)

**Comment by justchokingaround** [comment]
fixed it thx

**Comment by enimax-anime** [comment]
Oh. I have never encountered that. That's really weird. Maybe it was their WAF? 

Nice!!

**Comment by justchokingaround** [comment]
mayhaps, very weird though
