### ISSUE TITLE
ongoing anime series not displaying the proper latest episode range

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/jerry#28]
![1](https://github.com/justchokingaround/jerry/assets/95531944/504ce947-78ad-43ea-b675-22df79343f03)
![2](https://github.com/justchokingaround/jerry/assets/95531944/f0aa4910-b8e0-4f6d-a5f4-02a7b627febc)

Plus the default provider 9anime sucks aniwatch already has like ep 1071 while 9anime doesnt

**Comment by justchokingaround** [comment]
i can't do anything about the episode number, since anilist doesn't have it. if you check one piece's page on anilist u'll see it says `?` for total number of episode. you can change your default provider by adding this line in your config `provider=zoro`

**Comment by ttx99** [comment]
thanks for clarifying.
