### ISSUE TITLE
Follow convention for yes/no questions

### ISSUE THREAD

**Issue by VegardMatthey** [justchokingaround/jerry#29]
Shouldn't line 164 be switched out to be consistent with convention? I made yes default since it is capitalized instead of no. If you don't want yes to be default the n should be capitalized instead.

Example of how it could be fixed if yes is the default:
```
printf "No configuration file found. Would you like to generate a default one? [Y/n] " && read -r generate
case "$generate" in
"No" | "no" | "n" | "N") exit 0 ;;
```

**Comment by justchokingaround** [comment]
yes should be the default. i forgot to implement it

**Comment by VegardMatthey** [comment]
Added in the PR

**Comment by justchokingaround** [comment]
tyyy :)
