### ISSUE TITLE
Update README to contain information on what Jerry does

### ISSUE THREAD

**Issue by Pjarky** [justchokingaround/jerry#3]
Currently I am under the assumption that Jerry is something similar to ani-cli, where you can search for and watch anime via the command line (as well as other misc. features). I have come across some issues, but I can't tell if what happens is supposed to happen or not. In order to let me (and others) post meaningful issues it would be fantastic if documentation revolving this project would be improved.

**Comment by justchokingaround** [comment]
yes, but since this was a premature release i haven't done so. will do soon :tm:

**Comment by justchokingaround** [comment]
done in dc607852f1f89bdd2913fd3531f5e089cb0f2b27
