### ISSUE TITLE
Blank output on running jerry

### ISSUE THREAD

**Issue by samtrek** [justchokingaround/jerry#31]
No output was generated when I run jerry , it online returns the command prompt and nothing more, However if I run it with as `jerry -j` it generates some outputs in the form of continue or search for a new episode. Currently using Jerry version 1.9.9, linux archlinux 6.1.50-1-lts, jerry was installed using the generic command you gave for linux

**Comment by justchokingaround** [comment]
can u send some logs pls?

```sh
sh -x $(which jerry) -d 2>&1 | tee 2>&1 jerry.log
token=$(cat jerry.log | sed -nE "s@.*access_token=(.*)@\1@p" | head -1)
sed -i "/${token}/d" jerry.log
```

the jerry.log file in the current working directory is what i need

**Comment by samtrek** [comment]
https://pastebin.pl/view/b705a7c5

**Comment by justchokingaround** [comment]
are u trying to use ur anilist account with jerry or not?

**Comment by samtrek** [comment]
At first launch it asked for it, had to signup for it, from the log I sent to you the API key has been removed for security reasons.

**Comment by justchokingaround** [comment]
does `cat /home/jerry_user/.local/share/jerry/anilist_user_id.txt` return a token?

**Comment by samtrek** [comment]
no there is no directory named jerry under ~/.local/share/ and no file named anilist_user_id.txt

**Comment by samtrek** [comment]
no token the file is empty, do I have to add my id to the file?

**Comment by samtrek** [comment]
I added my username to the ~/.local/share/jerry/anilist_user_id.txt and now it does not return back to the command prompt.

**Comment by justchokingaround** [comment]
> no token the file is empty, do I have to add my id to the file?

no

**Comment by justchokingaround** [comment]
can u remove that file, and just run jerry again pls?

**Comment by samtrek** [comment]
I am sorry, I did not follow the link that came with the first launch, I generated my own personal api key and inserted it into the command prompt. I clicked on the link and it generated a new oath for me, it is working fine now, sorry for the mishap once again.

**Comment by justchokingaround** [comment]
np, happens!
