### ISSUE TITLE
WIndows Version

### ISSUE THREAD

**Issue by KememChan** [justchokingaround/jerry#33]
can you add this to windows?

**Comment by justchokingaround** [comment]
it's already supported, i just never documented it

**Comment by ttx99** [comment]
@justchokingaround 
pls provide quick guide here in this thread how to install it windows just comment here pls dude

**Comment by justchokingaround** [comment]
yeah sure, when i get some time i can make a video, if i forget please remind me in a week, i'm a bit busy atm

**Comment by RioNight** [comment]
You might just need to change all occurrences of `mpv` to `mpv.exe`.

**Comment by justchokingaround** [comment]
done and explained in 65f745532311051a5528f80e94ff330cdf9a8bd2

if u have more questions first check the wiki https://github.com/justchokingaround/jerry/wiki

if it's still unclear, re-open this issue or ask me directly
