### ISSUE TITLE
empty list

### ISSUE THREAD

**Issue by pr0k41** [justchokingaround/jerry#37]
Once i run jerry, i get the drop down and when i select any of them and search anything, it gives a blank output.

**Comment by justchokingaround** [comment]
can you send me a log, after running this command please, so i can check what went wrong? (it will create a file named `jerry.log` in the current directory)

```sh
sh -x $(which jerry) -c 2>&1 | tee jerry.log
token=$(cat jerry.log | sed -nE "s@.*access_token=(.*)@\1@p" | head -1)
sed -i "/${token}/d" jerry.log
```

**Comment by pr0k41** [comment]
[jerry.log](https://github.com/justchokingaround/jerry/files/12915988/jerry.log)

**Comment by justchokingaround** [comment]
i had to delete the log, bc it contained your user token (dw i won't do it anything with it, but there might be malicious people on the internet). it seems like your anime list only contains one entry: Monster. is that right? this might be an edge case i didn't consider (a single entry in the list). if yes, can you try adding another anime to the list and see whether it's still broken?

**Comment by pr0k41** [comment]
oh ohkayy, well i dont only have monster in my list, I have a lot more. I still added beyblade to my list to check but it did not help, it is still broken

**Comment by justchokingaround** [comment]
i'll investigate further later then

**Comment by Sridou** [comment]
I have the same issue after installing jerry in a fresh installation.

**Comment by pr0k41** [comment]
> i'll investigate further later then

ohkay

**Comment by justchokingaround** [comment]
the anilist API is down in some countries, due to cloudflare, so there isn't much i can do to fix it

**Comment by pr0k41** [comment]
so will it be up again or is it just gone?

**Comment by justchokingaround** [comment]
it should be back again in some time

**Comment by pr0k41** [comment]
ohkayy

**Comment by Sridou** [comment]
It's working for me now without me having to do anything

**Comment by pr0k41** [comment]
> It's working for me now without me having to do anything

yaa its fixed noww
