### ISSUE TITLE
Be able to set your Anilist API key in the config file.

### ISSUE THREAD

**Issue by allusive-dev** [justchokingaround/jerry#38]
For the sake of reproducabiity and simplicity would it be possible to store the Anilist API key in the configuration at `$PWD/.config/jerry/jerry.conf`?

**Comment by justchokingaround** [comment]
i don't think it's a good idea, that would be pretty bad for security. i should however document that the token is stored in `~/.local/share/jerry/anilist_token.txt`

**Comment by allusive-dev** [comment]
> i should however document that the token is stored in `~/.local/share/jerry/anilist_token.txt`


All good then, thank you very much.
