### ISSUE TITLE
Notify the user if they are missing a dependency

### ISSUE THREAD

**Issue by Pjarky** [justchokingaround/jerry#4]
I had been missing a dependency for a while now. Without the dependency, the command (when using -i flag) would just state: 
`Disclaimer: you need to finish the first episode before you can update your progress` 
and yield the command line forever. 
Today I downloaded mpv from the software store and now when attempting to watch Blue Lock said:
`Watching Blue Lock - Ep: 1 Dream`. 
Still didn't seem to do anything. 
I then uninstalled mpv and reinstalled it from the command line. It now works flawlessly.
It would be nice if the user (when using a command) was notified that they are missing something or if a specific error happened. This would've helped me a lot earlier.
(also, I used `jerry -i blue lock -n 1` everytime I attempted to get it working, if that's important.)

**Comment by justchokingaround** [comment]
thank you for letting me know, i'll implement it in thr next commit :+1:

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/jerry/commit/ca360ee7894815aeacf20faac0068f072dcd71de
