### ISSUE TITLE
Add support for REPEATING status

### ISSUE THREAD

**Issue by diniamo** [justchokingaround/jerry#46]
#45 does this for the "watch anime" menu, but nothing else.

Other places where this is needed:
- [x] Watch anime
- [ ] Read manga
- [ ] Update menus
  - [ ] Episodes watched
  - [ ] Chapters read
  - [ ] Change status
  - [ ] Change score

**Comment by diniamo** [comment]
I mean if it works, then yeah. Have you tested all of the listed features?

**Comment by Ar4m1s** [comment]
Yeah, no does not work currently.

**Comment by Ar4m1s** [comment]
It should work now, if you can prove otherwise, I'll fix it.

**Comment by diniamo** [comment]
nah too lazy
