### ISSUE TITLE
Use IINA instead of MPV

### ISSUE THREAD

**Issue by allusive-dev** [justchokingaround/jerry#5]
So i dont like using mpv, is there a way I can use VLC to watch animes instead?

**Comment by justchokingaround** [comment]
sure, but that'll affect other features such as resume from history. i'll trybto implement something later this week

**Comment by Poloniumx86** [comment]
And iina for macos and linux, much better ui + ani-cli uses it <3

**Comment by justchokingaround** [comment]
iina isn't supported on linux since it's written in swift. if there is a way to extract current progress in a video being played by it, i will look into implementing it

**Comment by allusive-dev** [comment]
Lol this issue is still active

**Comment by allusive-dev** [comment]
Since i created this issue i have just kept using MPV without any issues so @justchokingaround if you don't feel like making it work for VLC then I'm not too worried anymore.

**Comment by justchokingaround** [comment]
i'm not entirely against the idea of adding vlc support, the main problem is that the way the history feature is currently implemented, relies on the fact that you can extract the current progress of the currently playing video, which is not possible to do using vlc (afaik)

**Comment by justchokingaround** [comment]
it seems like it won't be possible to implement history tracking with iina using stderr information, however it is doable using mpv's ipc socket, which should be good enough i think. here is a reference that can be used for this implementation:
https://github.com/justchokingaround/lobster/blob/72b5752df1251d33c12a7f81627d1d20413be819/lobster.sh#L293-L319

**Comment by sneazy-ibo** [comment]
so is this going to be implemented or not?

**Comment by justchokingaround** [comment]
ongoing issue

**Comment by justchokingaround** [comment]
done in 9238e6e3e93305ac4db68d9dc897a5ef105d55f4

i didn't implement history by minutes support as none of the methods i tried seemed to be consistently working. i will keep that feature in mind, but gonna close this issue now, since the players are technically supported now
