### ISSUE TITLE
image preview not working on fzf

### ISSUE THREAD

**Issue by on-ii** [justchokingaround/jerry#52]
image preview not working on fzf. works fine on rofi.

To Reproduce,
1. jerry -i -c
2. select anime. 
3. instead of seeing a nice image preview i get [this](https://ibb.co/HGr67nJ)

Jerry Version: 1.9.9
here's my [log](https://pastebin.com/XwQfdJv3). i have removed my user id and username.

**Comment by justchokingaround** [comment]
can u share ur ueberzugpp config pls

**Comment by justchokingaround** [comment]
also made ueberzugpp optional in c684ac2

**Comment by on-ii** [comment]
> can u share ur ueberzugpp config pls

unfortunately i couldn't find any config for ueberzugpp. not even default ones. 
i have these variables on my jerry.conf if that help.
`preview_window_size=50%` 
`ueberzug_x=$(($(tput cols) - 70))`
`ueberzug_y=$(($(tput lines) / 10))`
`ueberzug_max_width=100`
`ueberzug_max_height=100`

**Comment by on-ii** [comment]
> can u share ur ueberzugpp config pls

unfortunately i couldn't find any config for ueberzugpp. not even default ones.
i have these variables on my jerry.conf if that help.
`preview_window_size=50%`
`ueberzug_x=$(($(tput cols) - 70))`
`ueberzug_y=$(($(tput lines) / 10))`
`ueberzug_max_width=100`
`ueberzug_max_height=100`

**Comment by justchokingaround** [comment]
try updating and using the new preview method without uz++ (it's the default now, so u dont need to change anything in ur jerry cfg)

**Comment by on-ii** [comment]
terminal gets filled with random [texts](https://ibb.co/L9RzDQC) now. tried different terminals, same issue.

**Comment by justchokingaround** [comment]
do u use kitty?

**Comment by justchokingaround** [comment]
ye thats why. it doesnt support sixel. ill lyk when i implement kitty

**Comment by justchokingaround** [comment]
done in 9238e6e3e93305ac4db68d9dc897a5ef105d55f4

in your jerry config specify `chafa_method="kitty"`
