### ISSUE TITLE
Make notifications transient with 'notify-send -e'

### ISSUE THREAD

**Issue by SsubezZ** [justchokingaround/jerry#58]
Notifications pile up in notification daemon like SwayNotificationCenter 

![2024-03-17-125948_hyprshot](https://github.com/justchokingaround/jerry/assets/119054422/44de1f48-b903-4438-996a-258abebcbd49)

or replace the old notification with 'notify-send -r'

**Comment by justchokingaround** [comment]
done in 9238e6e3e93305ac4db68d9dc897a5ef105d55f4
