### ISSUE TITLE
Publishing to nixpkgs

### ISSUE THREAD

**Issue by arunoruto** [justchokingaround/jerry#60]
It would be awesome to have jerry installable using nix.
I don't have much experience with publishing to nixpkgs, but I would be willing to try it out and help you with it!

**Comment by justchokingaround** [comment]
@diniamo

**Comment by diniamo** [comment]
I'm against that, just use the flake.

We can think about trying to get lobster and jerry on nixpkgs once they are rewritten.

**Comment by justchokingaround** [comment]
@arunoruto here are the relevant lines if u wanna install it using the flake

https://github.com/diniamo/niqs/blob/main/flake.nix#L29-L32
https://github.com/diniamo/niqs/blob/f20ba534c87bebb1259f352da003185bb7a77588/home-manager/jerry.nix#L1C2-L9
