### ISSUE TITLE
Cant fully paste my access token

### ISSUE THREAD

**Issue by mauriciopolvora** [justchokingaround/jerry#77]
When first running jerry and prompting me to paste my access token and trying to paste it does nothing and i cant click enter, when checking the diffs it seems once i paste the access token becomes different what can be the cause?

**Comment by justchokingaround** [comment]
the way your terminal handles input, your clipboard manager, or a lot of other things. you can always manually add your token by creating (in case it doesn't exist) the file `~/.local/share/jerry/anilist_token.txt` and then just pasting the token in there

**Comment by mauriciopolvora** [comment]
Thank you, adding it manually fixed it

**Comment by mauriciopolvora** [comment]
Thank you adding it manually fixed it
