### ISSUE TITLE
Discord RPC (Open with Vesktop)

### ISSUE THREAD

**Issue by JumperTheHero** [justchokingaround/jerry#78]
Hey! I really love using jerry! This is an upgrade for me personally compared to using ani-cli. So much customization and I love it. Got Discord RPC working through native Discord on Arch Linux but I personally use Vesktop as Xorg Screensharing works well with audio through it. Since Vesktop is just an extension of Discord, do you know where in the config or if it would be possible to have Discord RPC work with Vesktop?

**Comment by justchokingaround** [comment]
it works the same, i've tested in the past. u don't need to change anything

**Comment by JumperTheHero** [comment]
@justchokingaround Thanks! I'll look into it more. Last question, how did you setup your terminal to look so sexy in that demo? I love it! I think it might be the rofi themes, but unsure. Thanks again!

**Comment by justchokingaround** [comment]
it's just cool-retro-term and i'm using wayland as the output method in my ueberzugpp config. here is the cool-retro-term config:
```json
{
  "backgroundColor": "#000000",
  "fontColor": "#9b74ff",
  "flickering": 0.5,
  "horizontalSync": 0,
  "staticNoise": 0.1019,
  "chromaColor": 1,
  "saturationColor": 1,
  "screenCurvature": 0,
  "glowingLine": 0,
  "burnIn": 0.051,
  "bloom": 0.5,
  "rasterization": 0,
  "jitter": 0.0478,
  "rbgShift": 0,
  "brightness": 0.4812,
  "contrast": 1,
  "ambientLight": 0.3503,
  "windowOpacity": 0,
  "fontName": "System: IBM Plex Mono Text",
  "fontWidth": 1,
  "margin": 1,
  "blinkingCursor": true,
  "frameMargin": 0,
  "name": "main",
  "version": 2
}
```

**Comment by JumperTheHero** [comment]
@justchokingaround Where is the config file located? I apologize if I am asking too much, lol. Thanks again for the speedy reply!

**Comment by justchokingaround** [comment]
store it wherever you want. cool-retro-term allows you to import any custom json file u have on ur computer after u right click on it

**Comment by JumperTheHero** [comment]
Cool! Thanks again!
