### ISSUE TITLE
Change tmp/jerry_position file location?

### ISSUE THREAD

**Issue by tkjhamak1** [justchokingaround/jerry#82]
I managed to get Jerry running on Termux but the tmp files are not accessible to jerry
''sed: can't read /tmp/jerry_position: No such file or directory''

I couldn't find a way to change that file location in the config file; only the history is listed on the wiki.
Any help would be appreciated

**Comment by tkjhamak1** [comment]
I've found the proper variables 
tmp_dir & tmp_position
But I still get the same error. 
If I make directories for it, the errors stop for one run; are deleted; the position is not saved; the error comes back.

**Comment by tkjhamak1** [comment]
Found the proper dirs for termux
tmp_dir="/data/data/com.termux/files/usr/tmp/jerry"
tmp_position="/data/data/com.termux/files/usr/tmp/jerry_position"

**Comment by tanveer-vision** [comment]
brother it's just this much --

```sh
tmp_dir="${TMPDIR:-/tmp}/jerry"
tmp_position="${TMPDIR:-/tmp}/jerry_position"
```

takes care of temp directory on termux, and doesn't affect any other.

**Comment by CoolnsX** [comment]
brother it's just this much --

```sh
tmp_dir="${TMPDIR:-/tmp}/jerry"
tmp_position="${TMPDIR:-/tmp}/jerry_position"
```

takes care of temp directory on termux, and doesn't affect any other OS.
