### ISSUE TITLE
no progress on Mac os

### ISSUE THREAD

**Issue by i0rxg** [justchokingaround/jerry#89]
<img width="798" alt="Screenshot 2024-10-09 at 16 25 10" src="https://github.com/user-attachments/assets/8c3d0b57-a75c-409a-ace2-c4035cddee9f">
it stuck here, i don't know why, i have tried other terminal emulators but no luck.

**Comment by justchokingaround** [comment]
![Screenshot_20241009-213825.png](https://github.com/user-attachments/assets/3d10f736-f8ff-4bc2-8938-1e5439c1798c)
